- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingOption.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/CatalogItemDetails.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/adapters/OptionsAdapter.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/adapters/RadioAdapter.java
- traveler_ui_kit/src/main/res/layout/view_item.xml
**Note:** Can't test this right now as disclaimer is not available on dev API endpoint
> feat(core): adds disclaimer field to CatalogItemDetails and BookingOption

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Session.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Traveler.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/tasks/AuthTokenFetchTask.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/tasks/AuthenticatedRemoteNetworkRequestTask.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/tasks/SessionBeginTask.java
Add sandbox mode header to all calls
http://guestlogix.atlassian.net/jira/software/projects/TPP/boards/4?label=Android&selectedIssue=TPP-924
> Add sandboxMode to all calls.

- traveler_app/build.gradle
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Traveler.java
Fixes local.properties key to traveler_api_key_debug.
> Fixes local.properties key to traveler_api_key_debug.

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Airport.java
Fixes parsing for Airport object.
> Fixes parsing for Airport object.

- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/adapters/OptionsAdapter.java
> feat(core): adds check for null disclaimer

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Traveler.java
chore(core): standardizes initialize check across static methods within Traveler.java.
> chore(core): standardizes initialize check across static methods within Traveler.java.

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/OrderResult.java
https://guestlogix.atlassian.net/browse/TPP-1037
> fix(core): fixes nullability check in OrderResult.

- traveler_stripe_payment_provider/src/main/java/com/guestlogix/traveler_stripe_payment_provider/StripePayment.java
> feat(stripe): Exposes Card Brand via StripePayment attributes.

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/OrderStatus.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/PaymentInfo.java
> feat(core): Adds getter to OrderStatus.code

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/CancellationQuote.java
> fix(core): Fixes date parsing inside cancelationQuote.

- traveler_stripe_payment_provider/src/main/java/com/guestlogix/traveler_stripe_payment_provider/StripePayment.java
> Adds LastFourDigits to StripePayment Attributes.

- traveler_stripe_payment_provider/proguard-rules.pro
> fix(stripe): fixes proguard stripping out files under stripe module.

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Session.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Traveler.java
https://guestlogix.atlassian.net/browse/TPP-924
> feat(core): applies sandbox mode to calls

- gradle.properties
> Changes stripe key to live in release

- traveler_app/src/main/java/com/guestlogix/traveler/network/GuestRoute.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
> Makes default base url and lambda function point to production

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Traveler.java
https://guestlogix.atlassian.net/jira/software/projects/TPP/boards/4?label=Android&selectedIssue=TPP-1066
> fix(core): Fixes crash when initializing without network.

- traveler_app/src/main/java/com/guestlogix/traveler/network/GuestRoute.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/UrlRequest.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/tasks/NetworkTask.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/utilities/JsonObjectMapper.java
had to load the whole Json to memory to log the response in debug mode. in release mode there is no log and therefore no probable memory problem in production.
> add detailed log for network requests and responses

- traveler_stripe_payment_provider/src/main/java/com/guestlogix/traveler_stripe_payment_provider/StripePayment.java
> feat(stripe): extract StripePayment attribute keys to constants.

- traveler_app/src/main/java/com/guestlogix/traveler/application/TravelerApplication.java
> fix(core): Sandbox mode to on by default.

- traveler_ui_kit/src/main/res/layout/activity_cancel_order.xml
> change cancel button label

- traveler_app/src/main/java/com/guestlogix/traveler/application/TravelerApplication.java
> fix(core): fixes issue with endpoints always overwritten

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/callbacks/WishlistItemChangedCallback.java
> fix(core): fix javadoc linking causing an error on bintray upload.

- traveler_app/src/main/java/com/guestlogix/traveler/application/TravelerApplication.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/callbacks/EphemeralKeyFetchCallback.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/callbacks/PaymentSaveCallback.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/callbacks/PaymentsFetchCallback.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingItemDetails.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/EphemeralKey.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/EphemeralKeyError.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/PaymentManager.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Traveler.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/utilities/JsonObjectMapper.java
- traveler_stripe_payment_provider/build.gradle
- traveler_stripe_payment_provider/src/main/java/com/guestlogix/traveler_stripe_payment_provider/PaymentCollectionActivity.java
- traveler_stripe_payment_provider/src/main/java/com/guestlogix/traveler_stripe_payment_provider/PaymentSaveError.java
- traveler_stripe_payment_provider/src/main/java/com/guestlogix/traveler_stripe_payment_provider/StripePaymentManager.java
- traveler_stripe_payment_provider/src/main/java/com/guestlogix/traveler_stripe_payment_provider/StripePaymentProvider.java
- traveler_stripe_payment_provider/src/main/java/com/guestlogix/traveler_stripe_payment_provider/TravelerEphemeralKeyProvider.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/TravelerUI.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/OrderSummaryActivity.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/QuestionsActivity.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/fragments/BillingInformationCollectionFragment.java
- traveler_ui_kit/src/main/res/layout/fragment_billing_information_collection.xml
- traveler_ui_kit/src/main/res/values/strings.xml
i rebase ata's branch with master and resolved the conflicts.
> rebased save credit card

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/CatalogQuery.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/fragments/BookingItemDetailsFragment.java
- traveler_ui_kit/src/main/res/layout/fragment_catalog_item_details.xml
> feat(core): Extends CatalogQuery - feat(ui): Adds similar items

- traveler_ui_kit/src/main/res/layout/fragment_catalog_item_details.xml
- traveler_ui_kit/src/main/res/values/styles.xml
fixes two tickets : tpp-1367 and tpp-1369
https://guestlogix.atlassian.net/browse/TPP-1367
https://guestlogix.atlassian.net/browse/TPP-1369
> feat(ui): fixes bug with material tablayout

- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/FindParkingActivity.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/ParkingActivity.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/PassSelectionActivity.java
> fix(ui): fixes the null toolbar problem on parking views

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingItemSearchResult.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/ParkingItemSearchResult.java
> fix(core): fixes index out of bound problem with search results.

- traveler_ui_kit/src/main/AndroidManifest.xml
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/OrderSummaryActivity.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/QuestionsActivity.java
Fixes not clickable similar experiences (due to "singleTop" flag for activity)
* Fixes #
https://guestlogix.atlassian.net/browse/SDK-27 
* Connects #
> fix(ui): fixes not clickable similar experiences

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
Encodes date parameters before passing to back-end. Fixes related issues
* Fixes #
https://guestlogix.atlassian.net/browse/SDK-45
* Connects #
> fix(core): encodes date parameters

- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/itinerary/ItineraryFilterDialog.java
Flight category wasn't appearing on Filter popup for itinerary. This PR fixes that
> fix(ui): add flights to filter list

- traveler_ui_kit/src/main/res/layout/form_button.xml
> fix(ui): removes material button used in question form to fix WL crash

- traveler_ui_kit/src/main/res/layout/fragment_billing_information_collection.xml
Fixes an error which raises in WLA when trying to pay for a parking
* Fixes #
* Connects #
> fix(ui): material button on payment form

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/CatalogQuery.java
Adds city param to CatalogQuery to enable search for specific city
* Fixes #
* Connects #
> feat(core): Add city to CatalogQuery

- build.gradle
> fix(ui): updates core sdk version used in ui sdk

- build.gradle
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/BookingSearchActivity.java
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/CategoryAdapter.java
* Fixes #
https://guestlogix.atlassian.net/browse/SDK-51
https://guestlogix.atlassian.net/browse/WA-377
* Connects #
> feat(ui): use new dynamic categories for ui SDK-51 WA-377

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingItemQuery.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingItemSearchParameters.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/CatalogQuery.java
> feat(core): adds location support to catalog query

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Order.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/OrderStatus.java
https://guestlogix.atlassian.net/browse/WA-358
> feat(core): WA-358:adds support for unsupported order statuses to core

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingItemQuery.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/DateRangeFilter.java
This PR will add DateRangeFilter field for BookingQuery which is translated to availability params for booking search
https://guestlogix.atlassian.net/browse/SDK-58
> feat(core): SDK-58 Add availability param to BookingQuery

- build.gradle
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/BookingSearchResultActivity.java
Upgrades UI SDK with new Core SDK version to support DateRange filter
> feat(ui): WA-386 Add new core version to ui sdk

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingItemSearchParameters.java
https://guestlogix.atlassian.net/browse/TPP-1531
* Fixes #
* Connects #
> fix(core): fixes home screen crash on queries with null city

- build.gradle
- traveler_ui_kit/src/main/java/com/guestlogix/traveleruikit/activities/BookingSearchActivity.java
https://guestlogix.atlassian.net/browse/TPP-1531
* Fixes #
* Connects #
> fix(ui): applies latest core changes on ui sdk

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingItemCategory.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/BookingItemSearchParameters.java
Fixes BookingItemSearchParameters parsing.
**Implemented the same way as it done in iOS part**
> fix(core): fixes categories parsing for search parameters

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/CatalogGroup.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/CatalogGroupListMappingFactory.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/QueryItem.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/QueryItemListMappingFactory.java
https://guestlogix.atlassian.net/browse/WA-408
* Fixes #
* Connects #
> feat(core): adds see all query to catalog group

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/CatalogGroup.java
https://guestlogix.atlassian.net/browse/WA-408
* Fixes #
* Connects #
> fix(core): adds getter for seeAllCategory in catalogGroup

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Order.java
- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/OrderDiscount.java
* Fixes #
* Connects #
https://guestlogix.atlassian.net/browse/WA-466
> feat(core): order discount info

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/Router.java
> fix(core): applying discount for order

- traveler_core_kit/src/main/java/com/guestlogix/travelercorekit/models/Traveler.java
https://guestlogix.atlassian.net/browse/WA-524
* Fixes #
* Connects #
> fix(core): Checks if error message is null before trying to log it
